### ISSUE TITLE
ploblems with ARUnity5.unitypackage on Unity for mac

### ISSUE THREAD

**Issue by marcionicolau** [artoolkit/arunity5#100]
I couldn't import and run or create any kind of scene or project in Unity 5.3f4 on mac os. All my attempt on two machines with same problem. I try too from github and nothing. Thanks in advance

**Comment by ThorstenBux** [comment]
Did you follow this guide:
http://artoolkit.org/documentation/doku.php?id=6_Unity:unity_getting_started

If yes, what is the error you are getting?

**Comment by marcionicolau** [comment]
Yes, I'm following these steps and when I try to put ARController in the project the unity says that I need to correct compiler error before go ahead.

**Comment by ThorstenBux** [comment]
Can you paste the error message please?

**Comment by marcionicolau** [comment]
I will put the screen shots as soon as possible. I'm away from office computer now

**Comment by marcionicolau** [comment]
Hi @ThorstenBux, today I try to follow [documentation](http://artoolkit.org/documentation/doku.php?id=6_Unity:unity_getting_started)  again and get 

> /Users/someuser/Test3/Assets/ARToolKit5-Unity/Scripts/Editor/ARTrackedCameraGizmo.cs(38,38): Error CS0246: The type or namespace name `ARMarker' could not be found. Are you missing an assembly reference? (CS0246) (Assembly-CSharp-Editor)

See attached some pictures

![captura de tela 2016-08-17 as 10 16 13](https://cloud.githubusercontent.com/assets/1499733/17737858/5f4b34ba-6465-11e6-843c-58e2a89a9110.png)

![captura de tela 2016-08-17 as 10 17 58](https://cloud.githubusercontent.com/assets/1499733/17737856/5f0e4942-6465-11e6-91d3-70d76f9a9abf.png)

Today I only import ARUnity5-5.3.2.unitypackage to new Unity project and can't follow ahead.

See attach the content of ~/Library/Logs/Unity/Editor.log


[Editor.log.zip](https://github.com/artoolkit/arunity5/files/422686/Editor.log.zip)

**Comment by ThorstenBux** [comment]
Hi, 

I just downloaded the package and imported it into Unity 5.3.4f1. 
 - No import errors

Also I ran the sample scene that comes with the package:
Project/Assets/ARToolKit5-Unity/Example Scenes
All works well on my side so it is a bit hard to analyse what is going-on on your machine.

Can you try the sample scene?

**Comment by marcionicolau** [comment]
Unfortunately, I could import and run on Windows but doesn't work on Mac. Like I said before, after import the Unity shows the error message and I couldn't do anything.

**Comment by ThorstenBux** [comment]
Hi @marcionicolau 
I got another pointer into the direction that there might be something amiss when using Unity 5.4.0. Can you try and downgrade to 5.3.4f1? That is where everything still runs. I'm in the middle of something and don't want to upgrade right now that is why I don't want to upgrade right now.

I'd highly appreciate if you could try the 5.3.4f1 Unity version.
https://unity3d.com/get-unity/download/archive?_ga=1.160198717.1498217150.1465512057

**Comment by macropp** [comment]
I had same kind of problems when I imported the package in Unity 5.5.0f3. I think it's because the package includes configuration files for some reason, which seems to be breaking things in unity. See screenshot below:
<img width="447" alt="screen shot 2016-12-22 at 12 41 16 pm" src="https://cloud.githubusercontent.com/assets/2283433/21427774/ea7d6d00-c86f-11e6-9db6-bc3bb2d65e2d.png">

It seems to work fine when you deselect the DLLs that are included in the Unity app itself and any preference files and configs.

_Note: I think I had to reinstall Unity to make it work again._

**Comment by ThorstenBux** [comment]
Thanks for posting the solution

**Comment by linojon** [comment]
I dont know why this is closed, it sitll exists in ARUnity5-5.3.2.unitypackage downloaded March 14, 2017.

**Comment by ThorstenBux** [comment]
Can you try and use the repository version? the Downloadable package is quite old, we haven't released a new version in a while.

**Comment by hakusaro** [comment]
I can confirm that this issue definitely exists with the 5.3.2 tools for OS X download on the website, but doing the steps above by removing DLLs from the import package worked like a charm. I didn't do anything else -- I was losing hope until I found this thread.

**Comment by the-max0r** [comment]
When downloading ARUnity5.unitypackage from this Git-Repository and importing it to current Unity 5.6, everything works. The problem exists in old versions from www.artoolkit.org. Therefore, the links have to be updated.

**Comment by markbroughton** [comment]
> Therefore, the links have to be updated.
Yes, the-max0r
Shocking, wasting peoples time by having outdated files when all it takes it a few minutes to update the files on the website. I have come across this so many times with example files and set up files it is so annoying and wastes so many peoples time. At least change the downloads on the website to link to github

**Comment by RakeshKoplodR** [comment]
Hi I have downloaded package from GIT repository. Still i am unable to import ARToolkit in Unity.
Here is the error message:

**TypeLoadException: Could not load type 'UnityEngine.Cloud.Service.CloudServiceConfig' from assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.**

I have tried importing many times, but no success. Can somebody help to resolve this.

**Comment by ThorstenBux** [comment]
#164

**Comment by ThorstenBux** [comment]
See here for more: #164

**Comment by ThorstenBux** [comment]
Just updated the package again maybe that helps

**Comment by ThorstenBux** [comment]
@RakeshKoplodR Is your issue resolved by now? Wich unity version are you using?

**Comment by RakeshKoplodR** [comment]
@ThorstenBux yes the issue has been resolved. I am using Unity 5.6.1f1.

**Comment by robozera** [comment]
Still not a closed issue.... Unity 2017 and ARToolkit 5 or 6 for MAC OS still not working. Even not importing the DLLs.
